### PR TITLE
install: Point to ./docker directory instead of Dockerfile

### PR DESCRIPTION
**Pull request by awelzel**
Closes zeek/zeek#2805.

### CODE REVIEW

**Comment by awelzel** [comment]
@bbannier also brought up the idea of putting back the old Dockerfile, though that would mostly be an example rather than what's actually being used to create the final container images.

**Comment by timwoj** [comment]
> @bbannier also brought up the idea of putting back the old Dockerfile, though that would mostly be an example rather than what's actually being used to create the final container images.

I think putting the Dockerfile in there would cause confusion about what it's used for.

**Review by timwoj — APPROVED** [review]

**Comment by awelzel** [comment]
I've made it a bit more verbose, but essentially the same.

**Comment by bbannier** [comment]
> @bbannier also brought up the idea of putting back the old Dockerfile, though that would mostly be an example rather than what's actually being used to create the final container images.

To be fair, I never suggested to put back dead unused code, but instead was wondering whether this would be another good reason to bring back a more simple `Dockerfile` (the other being that this would simplify the setup a lot where it currently requires careful interaction between Docker setups in multiple files, and a `Makefile`). AFAICT one reason for the current setup was the desire to mount in a local cache during `docker run` executing the Zeek build, but this should also be possible [directly in the `Dockerfile`](https://docs.docker.com/engine/reference/builder/#run---mount).

**Comment by awelzel** [comment]
Thanks @bbannier - I've opened https://github.com/zeek/zeek/issues/2810, but for now I'll move forward fixing the link.

**Comment by awelzel** [comment]
I've also pushed this into release/5.2.

**Pull request merged**
